//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionMobileAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SessaoMobileEntities : DbContext
    {
        public SessaoMobileEntities()
            : base("name=SessaoMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funcao> Funcao { get; set; }
        public virtual DbSet<Relatos> Relatos { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VFuncao> VFuncao { get; set; }
        public virtual DbSet<VUsuario> VUsuario { get; set; }
    }
}
