//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatos
    {
        public int id { get; set; }
        public string relato { get; set; }
        public string imagem { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<int> usuarioid { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
